# Generated by Django 6.0.7 on 2026-08-17 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
